### ISSUE TITLE
Takler ikke koordinatverdier med høyde

### ISSUE THREAD

**Issue by NilsIvarNes** [kartverket/Geonorge.Validator#1]
validator.geonorge.no gir følgende feilmelding når jeg prøver å laste opp en FKB 5.0 testfil med EPSG 5972. Se testfil på (f.eks.) http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-BygnAnlegg/5.0/eksempel/

![image](https://user-images.githubusercontent.com/102019320/169227703-0fc5ea66-bcd8-46b8-ab57-067119474e50.png)

**Comment by toragustavsen** [comment]
Hei!

Dette er for så vidt ikke feilmeldinger fra validatoren, men rett og slett "grunner" til at GML-filen ikke kan åpnes i kartvisningen. Kartvisningen støtter (per i dag) kun todimensjonale geometrier med koordinatreferansesystemene EPSG:25832, EPSG:25833 eller EPSG:25835.
